language: c

sudo: false

# 7.0 is the minimum supported racket version
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=7.0
    - RACKET_VERSION=7.1
    - RACKET_VERSION=7.2
    - RACKET_VERSION=7.3
    - RACKET_VERSION=7.4
    - RACKET_VERSION=7.5
    - RACKET_VERSION=RELEASE

# You may want to test against certain versions of Racket, without
# having them count against the overall success/failure.
matrix:
  allow_failures:
    - env: RACKET_VERSION=RELEASE
  fast_finish: true


before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
  - export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us
  - raco pkg install --link -n loci
  
script:
  - racket test/test_locus-context.rkt 4
  - racket test/test_locus-messaging.rkt 1 10
  - racket test/test_locus-messaging.rkt 2 10
  - racket test/test_locus-messaging.rkt 10 10
  - racket test/test_locus-messaging.rkt 15 10
  - racket test/test_locus-messaging.rkt 10 20
  - ! racket test/test_locus-error.rkt
  - racket test/test_locus-print.rkt

